### ISSUE TITLE
12:00 -> 13:00 and 00:00 -> 01:00 not displayed properly in 12h Time Display

### ISSUE THREAD

**Issue by johnwdobbin** [reini1305/digilog#1]
I think updating these two lines from `background_update_proc`

```
    if(hour==0)
      hour=1;
```

will do the trick.

EDIT: actually looked resources/images

**Comment by reini1305** [comment]
You are right this is a typo. Should be hour=12; I will fix this after my vacation next week! 
Thanks and Kind Regards,
Christian
Am 21.07.2015 9:46 nachm. schrieb john w dobbin notifications@github.com:I think removing these two lines from background_update_proc

```
if(hour==0)
  hour=1;
```

will do the trick.

**Comment by reini1305** [comment]
OK, I fixed it now. Thanks for pointing the error out!
